name: AUTOMERGE

on:
  pull_request_target:
    types:
      - labeled
  check_suite:
    types:
      - completed
jobs:
  automerge:
    name: AUTOMERGED
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_REMOVE_LABELS: "automerge"
          UPDATE_LABELS: "merged"