name: AUTOMERGE

on:
  check_suite:
    types:
      - completed
jobs:
  merge-me:
    name: MERGE
    runs-on: ubuntu-latest
    steps:
      - name: MERGING
        uses: ridedott/merge-me-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MERGE_METHOD: MERGE