name: Release

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: 'TESTING'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
      - name: 'Running tests'
        run: 'TODO TESTS'
