name: Release

on:
  push:
    branches: 
      - main

jobs:
  test:
    name: 'TESTING'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
      - name: 'Running tests'
        run: echo "TODO TESTS"

  bump:
    needs: test
    name: 'BUMP'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Bump Version
        uses: opspresso/action-version@master
    