name: Release

on:
  push:
    branches: 
      - main

jobs:
  test:
    name: 'TESTING'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
      - name: 'Running tests'
        run: echo "TODO TESTS"

  release:
    name: 'RELEASE'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: 'Checkout Repository'
        uses: 'actions/checkout@v2'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows
      - name: Release to GitHub
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: Iván Lynch
          GIT_AUTHOR_EMAIL: ivan.lynch@outlook.com.ar
          GIT_COMMITTER_NAME: Iván Lynch
          GIT_COMMITTER_EMAIL: ivan.lynch@outlook.com.ar
        run: npx semantic-release