name: Release

on:
  push:
    branches: 
      - main

jobs:
  test:
    name: 'TESTING'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
      - name: 'Running tests'
        run: echo "TODO TESTS"

  tag:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: tool3/bump@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          unrelated: true
  publisher:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: tool3/publisher@v1
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          scope: "@tool3"