name: "RELEASE"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "TAGGED RELEASE"
    runs-on: "ubuntu-latest"
    steps:
      - name: "BUILD TAG"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.jar